-- Aura Heritage - Final Fixed Schema
-- Run this in your Supabase SQL Editor

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category TEXT,
  description TEXT,
  image TEXT,
  images JSONB,
  stock INTEGER DEFAULT 0,
  featured BOOLEAN DEFAULT false,
  rating NUMERIC DEFAULT 0,
  reviews INTEGER DEFAULT 0,
  is_new BOOLEAN DEFAULT false,
  sizes JSONB,
  colors JSONB,
  specifications JSONB,
  "artisanStory" TEXT,
  status TEXT DEFAULT 'Published',
  "createdAt" TEXT NOT NULL
);

-- 2. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  "userId" TEXT,
  phone TEXT,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Shipped', 'In Transit', 'Delivered', 'Cancelled', 'Processing')),
  customer JSONB,
  "deliveryFee" NUMERIC DEFAULT 0,
  "deliveryDate" TEXT,
  "createdAt" TEXT NOT NULL
);

-- 2.1 Create Order Items Table (Relational tracking)
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id TEXT, 
  product_name TEXT,
  quantity INTEGER,
  price NUMERIC,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
  id TEXT PRIMARY KEY,
  "fullName" TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password TEXT,
  role TEXT DEFAULT 'user',
  avatar TEXT,
  bio TEXT,
  "isBlocked" BOOLEAN DEFAULT false,
  "createdAt" TEXT NOT NULL
);

-- 4. Create Support Messages Table
CREATE TABLE IF NOT EXISTS public.support_messages (
  id TEXT PRIMARY KEY,
  "userId" TEXT,
  "userName" TEXT,
  email TEXT,
  subject TEXT,
  message TEXT,
  status TEXT DEFAULT 'unread',
  "createdAt" TEXT NOT NULL
);

-- 5. Create Admin Login History Table
CREATE TABLE IF NOT EXISTS public.admin_login_history (
  id TEXT PRIMARY KEY,
  "adminId" TEXT,
  "adminName" TEXT,
  time TEXT,
  location TEXT,
  device TEXT
);

-- 6. Disable RLS for all tables to allow easy data storage during development
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_login_history DISABLE ROW LEVEL SECURITY;

-- 7. Enable Realtime correctly
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE 
    public.products, 
    public.orders, 
    public.order_items,
    public.customers, 
    public.support_messages, 
    public.admin_login_history;
COMMIT;
